/*Mostrar todas as compras agrupadas por FORMA_PGTO*/


select count (A.COMPRA_ID) as QTDE_venda, sum (A.valor) as valor_venda, A.id_forma_pgto, b.descricao
from compra A
inner join FORMA_PGTO b on b.ID_FORMA_PGTO=a.ID_FORMA_PGTO
group by A.id_forma_pgto,b.DESCRICAO


/*Mostrar todas as vendas agrupadas por FORMA_PGTO*/


select count (A.VENDA_ID) as QTDE_venda, sum (A.valor) as valor_venda, A.id_forma_pgto, b.descricao
from vendas A
inner join FORMA_PGTO b on b.ID_FORMA_PGTO=a.ID_FORMA_PGTO
group by A.id_forma_pgto,b.DESCRICAO


/*Mostrar todas as vendas agrupadas por FORMA_PGTO*/


select count (A.VENDA_ID) as QTDE_venda, sum (A.valor) as valor_venda, A.id_forma_pgto, b.descricao
from vendas A
inner join FORMA_PGTO b on b.ID_FORMA_PGTO=a.ID_FORMA_PGTO
where a.CADASTRO between '10.01.2023' and '13.01.2023'
group by A.id_forma_pgto,b.DESCRICAO



/*MOSTRAR O QUANTO COMPREI POR PERIODO AGRUPADO POR FORNECEDOR */

SELECT COUNT(A.COMPRA_ID), SUM(A.VALOR), A.FORNECEDOR_ID, B.NOME
FROM COMPRA A
INNER JOIN FORNECEDOR B ON B.FORNECEDOR_ID = A.FORNECEDOR_ID
where a.CADASTRO between '10.01.2022' and '13.01.2023'
GROUP BY A.FORNECEDOR_ID, B.NOME


/* MOSTRAR O QUANTO PAGAMOS EM PERIODO AGRUPADO POR FORNECEDORES */

SELECT COUNT(A.COMPRA_ID), SUM(A.TOTAL_PAGAR), C.FORNECEDOR_ID, C.NOME FROM CONTAS_PAGAR A
INNER JOIN COMPRA B ON B.COMPRA_ID = A.COMPRA_ID
INNER join FORNECEDOR C ON C.FORNECEDOR_ID=B.FORNECEDOR_ID
WHERE A.STATUS='PAGO'
GROUP BY C.FORNECEDOR_ID, C.NOME



/*MOSTRAR O QUANTO TEMOS QUE PAGAR AGRUPADOS POR FORNECEDOR */ 

SELECT count(A.COMPRA_ID) AS QTDE_COMPRA, SUM(A.VALOR_PARCELA) AS VALOR_PAGAR, C.FORNECEDOR_ID, C.NOME 
FROM CONTAS_PAGAR A
INNER JOIN COMPRA B ON B.COMPRA_ID = A.COMPRA_ID
INNER JOIN FORNECEDOR C ON C.FORNECEDOR_ID = B.FORNECEDOR_ID
GROUP BY C.FORNECEDOR_ID, C.NOME
ORDER BY C.FORNECEDOR_ID


/* MOSTRAR O QUANTO COMPRAMOS POR MES*/

SELECT 
EXTRACT(MONTH FROM A.CADASTRO) AS MES,
EXTRACT(YEAR FROM A.CADASTRO) AS ANO,
SUM(A.VALOR) AS VALOR_COMPRA
FROM COMPRA A
WHERE A.CADASTRO BETWEEN '01.01.2022' AND '31.12.2023'

GROUP BY extract(MONTH FROM A.CADASTRO), extract(YEAR FROM A.CADASTRO)
ORDER BY EXTRACT(MONTH FROM A.CADASTRO)